http:
  routers:
    http-transaction-router: 
      rule: "Host(`eola.local`) && (PathPrefix(`/transaction`) ||  PathPrefix(`/transactions`)) && !Method(`OPTIONS`)"
      service : transaction-service
      middlewares:
      - cors-header
      - auth-middleware
      
    internal-http-transaction-router: 
      rule: "Host(`internal.eola.local`) && (PathPrefix(`/transaction`) ||  PathPrefix(`/transactions`)) && !Method(`OPTIONS`)"
      service : transaction-service
      middlewares:
      - cors-header

  middlewares:
    cors-header:
      headers:
        customResponseHeaders:
         Access-Control-Allow-Origin : "*"
    auth-middleware:
      forwardAuth:
        address: "http://eola.local/auth/current"
        authRequestHeaders:
          - "Authorization"
        authResponseHeaders:
          - "X-Auth-User"
          - "Authorization"
    replacepath:
      replacePath:
        path: "/auth/healthcheck"

  services:
    # Define how to reach an existing service on our infrastructure
    transaction-service:
      loadBalancer:
        servers:
        - url: http://localhost:8085



