http:
  routers:
    http-auth-router: 
      rule: "Host(`eola.local`) && PathPrefix(`/auth`)"
      service : auth-service
      middlewares:
      - cors-header

    internal-http-auth-router: 
      rule: "Host(`internal.eola.local`) && PathPrefix(`/auth`) && !Method(`OPTIONS`)"
      service : auth-service
      middlewares:
      - cors-header

  middlewares:
    cors-header:
      headers:
        customResponseHeaders:
         Access-Control-Allow-Origin : "*"

  services:
    # Define how to reach an existing service on our infrastructure
    auth-service:
      loadBalancer:
        servers:
        - url: http://tristan.pc:8082



