http:
  routers:
    http-front-router: 
      rule: "Host(`front.eola.local`)"
      service : front-service
      middlewares:
      - cors-header

  middlewares:
    cors-header:
      headers:
        customResponseHeaders:
         Access-Control-Allow-Origin : "*"

  services:
    # Define how to reach an existing service on our infrastructure
    front-service:
      loadBalancer:
        servers:
        - url: http://localhost:3000



